// Issue #1040: a single known trailing attribution block is outside canonical execution-plan
// fields. Fixtures are the verbatim #1037 Plan Index / unit-1037-A comment bodies.
// Run with: node --test tools/orchestration/attribution-suffix-1040.test.mjs
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { stripKnownAttributionSuffix, parseBulletBlock, parseExecutionPlan, classifyIntegrationRoute, planLevelRouteFailure } from "./parse-execution-plan.mjs";
import { findBulletFieldSpan, replacePrerequisitesDependenciesField } from "./correct-unit-dependency.mjs";
import { replaceRouteField } from "./correct-plan-index-route.mjs";

const dir = new URL("./fixtures/issue-1037-plan/", import.meta.url);
const planBody = readFileSync(new URL("plan-index.md", dir), "utf8");
const unitBody = readFileSync(new URL("unit-1037-A.md", dir), "utf8");
const unitB = readFileSync(new URL("unit-1037-B.md", dir), "utf8");
const unitC = readFileSync(new URL("unit-1037-C.md", dir), "utf8");
const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";

test("real #1037 plan index route is canonical, not contaminated", () => {
  const route = parseBulletBlock(planBody, "Integration/PR route");
  assert.equal(route, "integration worker");
  assert.equal(classifyIntegrationRoute(route).kind, "integration");
  assert.equal(parseBulletBlock(planBody, "Dependencies"), "1037-B depends on 1037-A; 1037-C depends on 1037-B");
});

test("real unit comment State parses without attribution; multiline fields intact", () => {
  assert.equal(parseBulletBlock(unitBody, "State"), "PLANNED");
  assert.match(parseBulletBlock(unitBody, "Required bounded outcome"), /^Obtain real evidence/);
});

test("full plan parse with decorated comments has no route failure", () => {
  const unit = (body, n) => ({ id: n, html_url: `https://github.com/o/r/issues/1037#issuecomment-${n}`, body });
  const plan = planBody
    .replace(/issuecomment-6090224124/, "issuecomment-11").replace(/issuecomment-6090224301/, "issuecomment-12").replace(/issuecomment-6090224510/, "issuecomment-13")
    .replace(/issuecomment-6090223945/, "issuecomment-10");
  const comments = [
    { id: 10, html_url: "https://github.com/o/r/issues/1037#issuecomment-10", body: "## Shared Contract (v1)\n\nx\n" },
    { id: 14, html_url: "https://github.com/o/r/issues/1037#issuecomment-14", body: plan },
    unit(unitBody, 11), unit(unitB, 12), unit(unitC, 13),
  ];
  const res = parseExecutionPlan(comments, { executionIssue: 1037 });
  const route = res.plan?.planIndex?.integrationRoute;
  assert.equal(route, "integration worker");
  assert.equal(planLevelRouteFailure(res.plan), null);
  for (const id of ["1037-A", "1037-B", "1037-C"]) {
    assert.equal(res.plan.units[id].fields?.state ?? res.plan.units[id].state, "PLANNED", id);
  }
});

test("verbatim 1037-B and 1037-C unit comments parse completely without attribution", () => {
  for (const [body, id, dep] of [[unitB, "1037-B", "1037-A"], [unitC, "1037-C", "1037-B"]]) {
    assert.equal(parseBulletBlock(body, "Unit ID"), id);
    assert.equal(parseBulletBlock(body, "State"), "PLANNED");
    assert.equal(parseBulletBlock(body, "Prerequisites/dependencies"), `Depends on ${dep}.`);
    assert.doesNotMatch(parseBulletBlock(body, "Durable output/state expected"), /Generated|---/);
    assert.equal(stripKnownAttributionSuffix(body), body.slice(0, body.lastIndexOf("---")).trimEnd());
  }
});

test("negative: one exact footer mid-body followed by more content is unchanged and contaminating", () => {
  const mid = `- **Integration/PR route:** integration worker

${FOOTER}

- **State:** PLANNED`;
  assert.equal(stripKnownAttributionSuffix(mid), mid);
  assert.notEqual(parseBulletBlock(mid, "Integration/PR route"), "integration worker");
  const bare = stripKnownAttributionSuffix(unitB);
  const midUnit = bare.replace("- **State:** PLANNED", `${FOOTER}

- **State:** PLANNED`);
  assert.notEqual(midUnit, bare);
  assert.equal(stripKnownAttributionSuffix(midUnit), midUnit);
  assert.match(parseBulletBlock(midUnit, "Interrupt/escalation conditions"), /Generated/);
});

test("strip: exactly one recognized block; CRLF; no-op otherwise", () => {
  assert.equal(stripKnownAttributionSuffix(`a\n\n${FOOTER}`), "a");
  assert.equal(stripKnownAttributionSuffix(`a\n\n${FOOTER}\n`), "a");
  assert.equal(stripKnownAttributionSuffix(`a\r\n\r\n${FOOTER.replace(/\n/g, "\r\n")}`), "a");
  assert.equal(stripKnownAttributionSuffix("a\n"), "a\n");
});

test("negative: second footer, modified footer, arbitrary prose stay contaminating", () => {
  const twice = `- **Integration/PR route:** integration worker\n\n${FOOTER}\n\n${FOOTER}`;
  assert.equal(stripKnownAttributionSuffix(twice), twice);
  assert.notEqual(parseBulletBlock(twice, "Integration/PR route"), "integration worker");
  const modified = `- **Integration/PR route:** integration worker\n\n---\n_Generated by [Other](https://x.example)_`;
  assert.notEqual(parseBulletBlock(modified, "Integration/PR route"), "integration worker");
  const prose = `- **Integration/PR route:** integration worker\n\n---\nsome prose`;
  assert.equal(classifyIntegrationRoute(parseBulletBlock(prose, "Integration/PR route")).kind !== "integration", true);
  const inField = `- **Integration/PR route:** integration worker ${FOOTER.replace("\n", " ")}`;
  assert.notEqual(parseBulletBlock(inField, "Integration/PR route"), "integration worker");
  const notBlank = `- **Integration/PR route:** integration worker\n${FOOTER}`;
  assert.notEqual(parseBulletBlock(notBlank, "Integration/PR route"), "integration worker");
});

test("continuations that belong to the value are preserved; suffix excluded", () => {
  const body = `- **A:** one\n  two\n- **B:** x\n  y\n\n${FOOTER}`;
  assert.equal(parseBulletBlock(body, "B"), "x y");
});

test("findBulletFieldSpan stops before the suffix; replaceRouteField preserves bytes and suffix", () => {
  const lines = planBody.split("\n");
  const span = findBulletFieldSpan(lines, "Integration/PR route");
  assert.deepEqual(lines.slice(span.startIdx, span.endIdx), ["- **Integration/PR route:** integration worker"]);
  const r = replaceRouteField(planBody, "unit-owned: 1037-C");
  assert.equal(r.ok, true);
  assert.equal(r.body, planBody.replace("integration worker", "unit-owned: 1037-C"));
  assert.equal(parseBulletBlock(r.body, "Integration/PR route"), "unit-owned: 1037-C");
});

test("dependency replacement on decorated unit preserves suffix and other lines", () => {
  const r = replacePrerequisitesDependenciesField(unitBody, ["1037-X"]);
  assert.equal(r.ok, true);
  assert.ok(r.body.trimEnd().endsWith(`\n\n${FOOTER}`));
  assert.equal(parseBulletBlock(r.body, "State"), "PLANNED");
  assert.equal(r.body.split("\n").length, unitBody.split("\n").length);
  assert.doesNotMatch(parseBulletBlock(r.body, "Prerequisites/dependencies"), /Generated/);
});

test("last field span on undecorated body unchanged", () => {
  const lines = "- **A:** 1\n- **B:** 2\n".split("\n");
  assert.deepEqual(findBulletFieldSpan(lines, "B"), { startIdx: 1, endIdx: 3 });
});
